name: Run Tests
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./scripts/build_and_run_tests.sh
         ./scripts/build_and_run_tests.sh
      shell: bash
